name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Login Docker Hub
      - name: Login Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 3. Build image
      - name: Build Docker image
        run: |
          VERSION="v1.${{ github.run_number }}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          docker build -t ${{ secrets.DOCKER_USERNAME }}/pokemon-app:$VERSION -t ${{ secrets.DOCKER_USERNAME }}/pokemon-app:latest .

      # 4. Push image
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/pokemon-app:$VERSION
          docker push ${{ secrets.DOCKER_USERNAME }}/pokemon-app:latest

           # - name: Deploy FE
      #   uses: appleboy/ssh-action@v0.1.6
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ubuntu
      #     key: ${{ secrets.EC2_SSH_KEY }}
      #     script: |
      #       cd ~/app
      #       docker pull ${{ secrets.DOCKER_USERNAME }}/frontend:latest
      #       docker-compose up -d frontend